CTOOLS-297: Updated configuration SDK generation
finbourne/lusid-sdk-generator-python pull request #34
Opened 2024-08-13 13:58 UTC by Matt-Storey-Finbourne

# Description of the PR

Fixed bug where self.access_token could become corrupted due to when creating an ApiClientFactory with FileTokenConfigurationLoader. Where the file path to the token became the actual token. 
A detailed breakdown of the bug can be found here at this [Jira](https://finbourne.atlassian.net/jira/software/c/projects/CTOOLS/boards/168/timeline?selectedIssue=CTOOLS-297)

2024-08-13 15:30 UTC, AndrewNeudegg requested changes

2024-08-13 15:30 UTC, AndrewNeudegg commented on generate/default_templates/pyproject.mustache
> +more-itertools = "10.4.0"
Do we want to introduce a new dependency? Is there a way to acheive what we want without this?

2024-08-13 15:30 UTC, AndrewNeudegg commented on generate/templates/pyproject.mustache
> +more-itertools = "10.4.0"
likewise

2024-08-13 15:30 UTC, AndrewNeudegg commented on generate/default_templates/pyproject.mustache
> +more-itertools = "10.4.0"
I can't see where this is used

2024-08-13 15:30 UTC, AndrewNeudegg commented on test_sdk/unit/test_api_client_factory.py
> +    @pytest.mark.asyncio
Would it be possible to test the case where it is a class and the case where it is a string as well as the sunshine path?

2024-08-13 15:36 UTC, Matt-Storey-Finbourne commented on generate/default_templates/pyproject.mustache
> +more-itertools = "10.4.0"
I needed this before I updated my branch with master. I'll check to see if its still required or not

2024-08-13 15:39 UTC, Matt-Storey-Finbourne commented on test_sdk/unit/test_api_client_factory.py
> +    @pytest.mark.asyncio
Yep that should be fine. I'll update the test

2024-08-14 07:13 UTC, cg-finbourne commented on generate/default_templates/configuration.mustache
> +            if isinstance(self.access_token, str):
has the indentation changed? if so, is that something we wanted - you could use the `compile-and-fly-test-pipeline.sh` in the sdk-pipeline repo to see how the sdks will change

2024-08-14 07:19 UTC, cg-finbourne commented on generate/default_templates/configuration.mustache
> +                print("The variable is of type str.")
is this debug logging, do we want to keep it?

2024-08-14 07:29 UTC, cg-finbourne commented on test_sdk/unit/test_api_client_factory.py
> +                response = await api_instance.get_lusid_versions_with_http_info()
is it possible to verify the correct behaviour via unit test without needing working credentials? I did a quick scan and it looked like the rest of the tests in this class are non integration tests (though could be wrong), it would be good to split the unit and integration tests so that the unit tests can be run locally without needing credentials, and be able to run as many tests as possible in the unit test phase (currently we don't separate them, but I have an mr for java to split and we might want to do for python as well)

2024-08-14 07:36 UTC, Matt-Storey-Finbourne commented on generate/default_templates/configuration.mustache
> +                print("The variable is of type str.")
Yep thats a debug log I'll remove it

2024-08-14 07:46 UTC, Matt-Storey-Finbourne commented on test_sdk/unit/test_api_client_factory.py
> +                response = await api_instance.get_lusid_versions_with_http_info()
So the actual error occurs when making a request as some validation is triggered when making a request.
I'm not sure if a mocking it will actually test this

2024-08-14 07:50 UTC, Matt-Storey-Finbourne commented on generate/default_templates/configuration.mustache
> +            if isinstance(self.access_token, str):
Yes I think it has changed. I assume I should do this after the merge?

2024-08-14 14:39 UTC, cg-finbourne commented on test_sdk/unit/test_api_client_factory.py
> +                config = file_token_loader.load_config()
you can use pytest.raises() to assert an exception of a specified type was thrown - https://docs.pytest.org/en/stable/how-to/assert.html#assertions-about-expected-exceptions

2024-08-15 15:22 UTC, AndrewNeudegg approved these changes

2024-08-15 15:24 UTC, merged